// <auto-generated />
using Atlas.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Atlas.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210128151836_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Atlas.Domain.Entities.RacingClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RacingClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PROD-32"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PROD-24"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Чайник",
                            Name = "ES-24U"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
